version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - ${PORT_MONGO:-27017}:${PORT_MONGO:-27017}
    volumes:
      - ${CONTEXT_MONGO:-./hitpoints-db-mongo}/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - ${CONTEXT_MONGO:-./hitpoints-db-mongo}/dump:/dump
      - ${CONTEXT_MONGO:-./hitpoints-db-mongo}/mongorestore.sh:/mongorestore.sh
      - ${CONTEXT_MONGO:-./hitpoints-db-mongo}/mongodump.sh:/mongodump.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD:-example}

  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - ${PORT_MONGO_EXPRESS:-8081}:${PORT_MONGO_EXPRESS:-8081}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD:-example}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER:-root}:${DB_PASSWORD:-example}@mongo:${DB_PORT-:27017}/

  api-express:
    depends_on:
      - mongo
    build:
      context: ${CONTEXT_EXPRESS:-./hitpoints-api-express}
      dockerfile: Dockerfile
    volumes:
      - .:/api-express
    ports:
      - ${PORT_EXPRESS:-8080}:${PORT_EXPRESS:-8080}
    environment:
      - PORT=${PORT_EXPRESS:-8080}
      - HOST=${HOST_EXPRESS:-0.0.0.0}
      - DB_URL = mongodb://${DB_USER:-root}:${DB_PASSWORD:-example}@${DB_HOST-:mongo}:${DB_PORT-:27017}/

  ui-vue:
    depends_on:
      - api-express
    build:
      context: ${CONTEXT_VUE:-./hitpoints-ui-vue}
      dockerfile: Dockerfile
    ports:
      - ${PORT_VUE:-80}:${PORT_VUE:-80}

  ui-react:
    depends_on:
      - api-express
    build:
      context: ${CONTEXT_REACT:-./hitpoints-ui-react}
      dockerfile: Dockerfile
    ports:
      - ${PORT_REACT:-80}:${PORT_REACT:-80}
